######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 23 18:15:50 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += profile_widget.h
SOURCES += main.cpp profile_widget.cpp
