######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 23 17:36:22 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
