######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 24 01:24:53 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11 -g

# Input
HEADERS += main_window.h post.h post_widget.h reddit.h
SOURCES += main.cpp main_window.cpp post.cpp post_widget.cpp reddit.cpp
